export { HeroSection } from './hero-section'
export { OfferSection } from './offer-section'
export { FitSection } from './fit-section'
export { ProofSection } from './proof-section'
export { FaqSection } from './faq-section'
export { StartSection } from './start-section'
