export { HeroSection } from './hero-section'
export { StatementSection } from './statement-section'
export { ProjectsSection } from './projects-section'
export { VoicesSection } from './voices-section'
export { TrustSection } from './trust-section'
export { BenefitsSection } from './benefits-section'
export { TrackingSection } from './tracking-section'
export { CtaSection } from './cta-section'
