/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RegisterResponseApiResponse"];
                        "application/json": components["schemas"]["RegisterResponseApiResponse"];
                        "text/json": components["schemas"]["RegisterResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["VerifyEmailRequest"];
                    "text/json": components["schemas"]["VerifyEmailRequest"];
                    "application/*+json": components["schemas"]["VerifyEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VerifyEmailResponseApiResponse"];
                        "application/json": components["schemas"]["VerifyEmailResponseApiResponse"];
                        "text/json": components["schemas"]["VerifyEmailResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResendVerificationRequest"];
                    "text/json": components["schemas"]["ResendVerificationRequest"];
                    "application/*+json": components["schemas"]["ResendVerificationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResendVerificationResponseApiResponse"];
                        "application/json": components["schemas"]["ResendVerificationResponseApiResponse"];
                        "text/json": components["schemas"]["ResendVerificationResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthTokensResponseApiResponse"];
                        "application/json": components["schemas"]["AuthTokensResponseApiResponse"];
                        "text/json": components["schemas"]["AuthTokensResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshTokenRequest"];
                    "text/json": components["schemas"]["RefreshTokenRequest"];
                    "application/*+json": components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthTokensResponseApiResponse"];
                        "application/json": components["schemas"]["AuthTokensResponseApiResponse"];
                        "text/json": components["schemas"]["AuthTokensResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                    "text/json": components["schemas"]["LogoutRequest"];
                    "application/*+json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LogoutResponseApiResponse"];
                        "application/json": components["schemas"]["LogoutResponseApiResponse"];
                        "text/json": components["schemas"]["LogoutResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ForgotPasswordRequest"];
                    "text/json": components["schemas"]["ForgotPasswordRequest"];
                    "application/*+json": components["schemas"]["ForgotPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ForgotPasswordResponseApiResponse"];
                        "application/json": components["schemas"]["ForgotPasswordResponseApiResponse"];
                        "text/json": components["schemas"]["ForgotPasswordResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ResetPasswordRequest"];
                    "text/json": components["schemas"]["ResetPasswordRequest"];
                    "application/*+json": components["schemas"]["ResetPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PasswordChangedResponseApiResponse"];
                        "application/json": components["schemas"]["PasswordChangedResponseApiResponse"];
                        "text/json": components["schemas"]["PasswordChangedResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                    "text/json": components["schemas"]["ChangePasswordRequest"];
                    "application/*+json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PasswordChangedResponseApiResponse"];
                        "application/json": components["schemas"]["PasswordChangedResponseApiResponse"];
                        "text/json": components["schemas"]["PasswordChangedResponseApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            code?: string | null;
            message?: string | null;
            details?: unknown;
        };
        AuthTokensResponse: {
            /** Format: uuid */
            userId?: string;
            accessToken?: string | null;
            /** Format: date-time */
            accessTokenExpiresAt?: string;
            refreshToken?: string | null;
            /** Format: date-time */
            refreshTokenExpiresAt?: string;
            tokenType?: string | null;
        };
        AuthTokensResponseApiResponse: {
            isSuccess?: boolean;
            traceId?: string | null;
            data?: components["schemas"]["AuthTokensResponse"];
            error?: components["schemas"]["ApiError"];
        };
        ChangePasswordRequest: {
            currentPassword?: string | null;
            newPassword?: string | null;
        };
        ForgotPasswordRequest: {
            email?: string | null;
        };
        ForgotPasswordResponse: {
            accepted?: boolean;
        };
        ForgotPasswordResponseApiResponse: {
            isSuccess?: boolean;
            traceId?: string | null;
            data?: components["schemas"]["ForgotPasswordResponse"];
            error?: components["schemas"]["ApiError"];
        };
        LoginRequest: {
            email?: string | null;
            password?: string | null;
        };
        LogoutRequest: {
            refreshToken?: string | null;
        };
        LogoutResponse: {
            accepted?: boolean;
        };
        LogoutResponseApiResponse: {
            isSuccess?: boolean;
            traceId?: string | null;
            data?: components["schemas"]["LogoutResponse"];
            error?: components["schemas"]["ApiError"];
        };
        PasswordChangedResponse: {
            passwordChanged?: boolean;
        };
        PasswordChangedResponseApiResponse: {
            isSuccess?: boolean;
            traceId?: string | null;
            data?: components["schemas"]["PasswordChangedResponse"];
            error?: components["schemas"]["ApiError"];
        };
        RefreshTokenRequest: {
            refreshToken?: string | null;
        };
        RegisterRequest: {
            email?: string | null;
            password?: string | null;
            fullName?: string | null;
            phone?: string | null;
        };
        RegisterResponse: {
            /** Format: uuid */
            userId?: string;
            email?: string | null;
            verificationRequired?: boolean;
        };
        RegisterResponseApiResponse: {
            isSuccess?: boolean;
            traceId?: string | null;
            data?: components["schemas"]["RegisterResponse"];
            error?: components["schemas"]["ApiError"];
        };
        ResendVerificationRequest: {
            email?: string | null;
        };
        ResendVerificationResponse: {
            accepted?: boolean;
        };
        ResendVerificationResponseApiResponse: {
            isSuccess?: boolean;
            traceId?: string | null;
            data?: components["schemas"]["ResendVerificationResponse"];
            error?: components["schemas"]["ApiError"];
        };
        ResetPasswordRequest: {
            token?: string | null;
            newPassword?: string | null;
        };
        VerifyEmailRequest: {
            token?: string | null;
        };
        VerifyEmailResponse: {
            emailVerified?: boolean;
        };
        VerifyEmailResponseApiResponse: {
            isSuccess?: boolean;
            traceId?: string | null;
            data?: components["schemas"]["VerifyEmailResponse"];
            error?: components["schemas"]["ApiError"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
